line-length = 110
indent-width = 4
target-version = "py38"

[format]
quote-style = "double"
indent-style = "space"


[lint]
select = ["F", "E", "W", "I", "UP", "B", "RUF"]
ignore = [
   "UP015" # Unnecessary open mode parameters
]
